### ISSUE TITLE
explain how to build container 

### ISSUE THREAD

**Issue by obker** [Secure-Compliance-Solutions-LLC/gitbook#12]
When building container, I get the error 

Step 23/41 : COPY apk-build/target/ /repo/
COPY failed: file not found in build context or excluded by .dockerignore: stat apk-build/target/: file does not exist

I cannot find the documentation for building the docker.

**Comment by austinsonger** [comment]
Speak of the devil, I was going to update some of the documentation and just came across this issue. @Dexus

**Comment by abnerrizzi** [comment]
Any news on this ?

**Comment by austinsonger** [comment]
Alpine is no longer part of this image.

**Comment by paalbra** [comment]
> Alpine is no longer part of this image.

What does this mean? The references to apk-build is still there and I can't find any build instructions.

I believe this issue is still relevant.
