### ISSUE TITLE
Mistake in the description of adding OpenVAS scanner to GVM via add-scanner.sh script.

### ISSUE THREAD

**Issue by rdruzhkov** [Secure-Compliance-Solutions-LLC/gitbook#16]
At page that describes [OpenVAS Scanner Image](https://securecompliance.gitbook.io/projects/openvas_image) one of the deployment steps is adding an OpenVAS scanner to GVM via add-scanner.sh script. Description of that process (quote below) is confusing. We need to pass scanner's private key when script (add-scanner.sh) asks for public.

> Scanner Name: **This can be anything you want** Scanner ID: **generated id from remote openvas scanner** Scanner public key: **private key from scanner**

I passed scanner's public key to add-scanner.sh script and it worked. I think there is a mistake in the description, isn't it?

**Comment by Dexus** [comment]
For further support, use https://github.com/DeineAgenturUG/greenbone-gvm-openvas-for-docker

**Comment by rdruzhkov** [comment]
I made a pull request #21 with changes that fix the description. Please, review it.

**Comment by rdruzhkov** [comment]
Stale.
