### ISSUE TITLE
PDF Reports out of docker container are 0 byte size - XML and TXT works fine

### ISSUE THREAD

**Issue by 4920441** [Secure-Compliance-Solutions-LLC/gitbook#17]
All is said in the Headline....

With the official Docker Container from GVM I get only 0 Byte sized PDF Records, which is a shame :-(

With other docker images (forks) I get pdf right on, but their problem is, that they are all using the outdated scanner-engine :-(

Did you forget to include the appropriate LaTex libraries/tools in your own docker image?

Cheers

**Comment by austinsonger** [comment]
@4920441 Please create the issue in the correct repo.

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/issues/new/choose
